"""
Utility script to find code files generated by Agile Factory.

Helps locate where DeepAgents stores files after code generation.
"""

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from agents.agile_factory.tools.workspace_locator import get_workspace_info, list_files_in_workspace


def main():
    """Find and display all code generation workspaces and files."""
    
    print("=" * 70)
    print("Agile Factory Code Files Location Finder")
    print("=" * 70)
    print()
    
    # Get workspace info
    ws_info = get_workspace_info()
    
    print(f"Project Root: {ws_info['project_root']}")
    print()
    
    # Check each workspace type
    found_files = False
    
    for ws_type, paths in ws_info["workspaces"].items():
        if paths:
            print(f"{ws_type.upper().replace('_', ' ')}:")
            print("-" * 70)
            for path in paths:
                print(f"  {path}")
                files = list_files_in_workspace(path)
                if files:
                    found_files = True
                    print(f"    Found {len(files)} files:")
                    for file_info in files[:10]:  # Show first 10 files
                        print(f"      - {file_info['path']} ({file_info['size']} bytes)")
                    if len(files) > 10:
                        print(f"      ... and {len(files) - 10} more files")
                else:
                    print(f"    (no files found)")
            print()
    
    # Show files by workspace
    if ws_info["files_by_workspace"]:
        print("FILES BY WORKSPACE:")
        print("-" * 70)
        for ws_type, workspaces in ws_info["files_by_workspace"].items():
            if workspaces:
                print(f"\n{ws_type}:")
                for ws_path, files in workspaces.items():
                    if files:
                        print(f"  {ws_path}:")
                        for file_info in files[:5]:
                            print(f"    - {file_info['path']}")
                        if len(files) > 5:
                            print(f"    ... and {len(files) - 5} more")
    
    if not found_files:
        print("WARNING: No code files found in any workspace!")
        print()
        print("Possible reasons:")
        print("  1. Code generation hasn't run yet")
        print("  2. DeepAgents stored files in an unexpected location")
        print("  3. Files were only stored in workflow state (check LangGraph Studio state)")
        print()
        print("Check these locations manually:")
        print(f"  - {project_root / 'agile_factory_workspace'}")
        print(f"  - {project_root / 'agile_workspace'}")
        print(f"  - {project_root / '.deepagents' / 'workspace'}")
        print(f"  - {Path.home() / '.deepagents' / 'workspace'}")
    else:
        print()
        print("=" * 70)
        print("Files found! Check the workspace paths above to access them.")
        print("=" * 70)


if __name__ == "__main__":
    main()

